version: '3'
services:
  api:
    build: ./backend
    ports:
      - '8000:8000'
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ragsaas
